Replug "Homepage Owl Carousel" to show Anime posts.
jefroy/wp-anime-review pull request #41
Opened 2020-04-04 02:31 UTC by matabeitt

Resolves #34 

This change was a bit more complicated, as the parent theme was making use of hooks inside the carousel tags to inject PHP from a script located in the hooks directory. I simply copied that template file and pasted it where the call was in the original function.

2020-04-04 02:32 UTC, matabeitt commented on public/wp-content/themes/newsup-child/functions.php
> +                                  $newsup_all_posts_main = newsup_get_posts($newsup_number_of_slides, $newsup_slider_category);
This is the beginning of the template. This template was taken from another file and pasted here to simplify the process of making this change.

2020-04-04 02:38 UTC, matabeitt commented on public/wp-content/themes/newsup-child/functions.php
> -                                                          <?php newsup_post_meta(); ?>
This function makes use of a template in newsup internal hooks. Let's just overwrite it by copy pasting because otherwise it would be a lot of work.

2020-04-04 16:36 UTC, matabeitt commented
Having an issue #44 adding files to child theme.

2020-04-04 16:52 UTC, asayee0 commented
> Added public/wp-content/themes/newsup-child/index.php to repo using `git add <index.php>`

I have no idea if this solution will uphold for later commits, but the problem is our .gitignore; it seems we've been doing that wrong somehow idk how.

2020-04-04 17:19 UTC, asayee0 requested changes
After reading the .gitignore man page, I believe I updated it so we should have no further problems with ignoring the themes folder.
Also removed .gitignore from child theme

2020-04-04 19:22 UTC, asayee0 approved these changes

2020-04-05 00:10 UTC, matabeitt commented
Resolves #36

2020-04-05 00:12 UTC, merged